import logging

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.core.config import settings

logger = logging.getLogger("pashurakshak")
from app.auth.router import router as auth_router
from app.users.router import router as users_router
from app.farms.router import router as farms_router
from app.animals.router import router as animals_router
from app.reports.router import router as reports_router
from app.cases.router import router as cases_router
from app.visits.router import router as visits_router
from app.treatment.router import router as treatment_router
from app.lab.router import router as lab_router
from app.vaccination.router import router as vaccination_router
from app.gis.router import router as gis_router
from app.alerts.router import router as alerts_router
from app.analytics.router import router as analytics_router
from app.sync.router import router as sync_router
from app.audit.router import router as audit_router
from app.weather.router import router as weather_router

app = FastAPI(
    title="PASHU-RAKSHAK AI",
    description="Detect Early • Respond Faster • Protect Livestock — SIH 2026 (PS 26128)",
    version="1.0.0-prototype",
)

for r in [
    auth_router, users_router, farms_router, animals_router, reports_router,
    cases_router, visits_router, treatment_router, lab_router,
    vaccination_router, gis_router, alerts_router, analytics_router,
    sync_router, audit_router, weather_router,
]:
    app.include_router(r, prefix=settings.API_V1_PREFIX)


# NOTE (SIH Round-2 non-seeded requirement): this application NEVER seeds
# demo/fake data automatically on startup, in any mode. A fresh database
# starts completely empty — 0 users, 0 farms, 0 animals, 0 reports, 0 cases —
# and every record must be created through the real registration/API flow
# (see app/auth/router.py: POST /auth/register, and app/core/db.py for the
# real-vs-in-memory persistence tradeoff).
#
# backend/seed/seed_data.py still exists as an OPT-IN developer convenience
# for local UI/demo walkthroughs. It is never imported or run by the app
# itself — it only runs if a developer explicitly executes
# `python -m seed.seed_data` themselves.


@app.on_event("startup")
def warn_if_not_persistent():
    """Loudly flag non-persistent storage. This must never be silent: a
    judge/evaluator restarting the backend against mongomock would see all
    data vanish and could mistake that for a real persistence bug."""
    logger.info("CORS allowed origins: %s", settings.CORS_ORIGINS)
    if settings.DEMO_MODE:
        logger.warning(
            "=" * 78 + "\n"
            "MONGODB_URI is not set — running on an IN-MEMORY database (mongomock).\n"
            "Data will NOT survive a backend restart. This mode is for local\n"
            "development convenience ONLY. Set MONGODB_URI to a real MongoDB\n"
            "instance before running the SIH judged demo. See .env.example.\n" + "=" * 78
        )


@app.get("/")
def root():
    return {
        "app": settings.APP_NAME,
        "tagline": "Detect Early • Respond Faster • Protect Livestock",
        "persistent_storage": not settings.DEMO_MODE,
        "storage_warning": None if not settings.DEMO_MODE else (
            "Running on in-memory storage (no MONGODB_URI set). Data will not "
            "survive a restart. Not suitable for evaluation/production."
        ),
        "docs": "/docs",
    }


@app.get("/health")
def health():
    return {"status": "ok", "persistent_storage": not settings.DEMO_MODE}


# Wrap the complete ASGI app so CORS headers are also applied to error
# responses generated by FastAPI's outer server-error middleware.
app = CORSMiddleware(
    app=app,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
